<!-- BEGIN head.inc -->

        <!-- build:remove

            sitewide <link> (read media specific css [print/screen/etc.])
            and meta elements go here

            concatenated and minified files are referenced below based on build name

            non-concatenated files are included below that within the build:remove block

        --><!-- /build -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <!-- build:css:debug ui/css/all.css --><!-- /build -->
        <!-- build:css:release ui/css/all_min.css --><!-- /build -->

        <!-- build:remove:debug,release -->
          <!-- ALL UNPROCESSED CSS FOR DEV GOES HERE!!!!! -->
        <!-- /build -->
        <!-- END head.inc -->