<!-- BEGIN head.inc -->
        <!-- build:remove

            sitewide <link> (read media specific css [print/screen/etc.]) 
            and meta elements go here
    
            concatenated and minified files are referenced below based on build name

            non-concatenated files are included below that within the build:remove block
        --><!-- /build -->
        
        <!-- build:css:debug ui/css/all.css --><!-- /build -->
        <!-- build:css:release ui/css/all_min.css --><!-- /build -->

        <!-- build:remove:debug,release -->
        
        <!-- /build -->
        
        <!-- END head.inc -->