<!-- BEGIN scripts.inc -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!-- build:js:debug ui/js/app.js --><!-- /build -->
        <!-- build:js:release ui/js/app_min.js --><!-- /build -->

        <!-- build:remove:debug,release -->
            <!-- local non-concatenated specialized scripts go here -->
        <!-- /build -->

        <!-- END scripts.inc -->